#!/usr/bin/env bash

function usage() {
  ME=$(basename $0)
    echo "Executes a pod for debugging purposes"
    echo ""
    echo "USAGE:"
    echo "$ME [-n [namespace]]"
    echo ""
    echo "EXAMPLES:"
    echo "$ME"
    echo "$ME -n mynamespace"
    return 0 2> /dev/null || exit 0
}

if [[ $* == "-h" ]]; then
  usage
  exit 0
fi

NAMESPACE_ARGS=""
if [[ $1 == "-n" ]]; then
  if [[ -z $2 ]]; then
      usage
      exit 0
  fi

  NAMESPACE_ARGS="-n $2"
fi


cat << EOF | kubectl $NAMESPACE_ARGS apply -f -
kind: Pod
apiVersion: v1
metadata:
  name: debugger-pod
  labels:
    app: debugger-pod
spec:
  containers:
  - name: debugger
    image: yngvark/linuxtools
EOF

kubectl $NAMESPACE_ARGS wait --for=condition=ready pod -l app=debugger-pod --timeout 60s
kubectl $NAMESPACE_ARGS exec -it debugger-pod -- bash && (kubectl delete pod debugger-pod || true)
