#!/usr/bin/env bash

#function usage() {
#  ME=$(basename $0)
#    echo "Executes a pod for debugging purposes"
#    echo ""
#    echo "USAGE:"
#    echo "$ME [-n [namespace]]"
#    echo ""
#    echo "EXAMPLES:"
#    echo "$ME"
#    echo "$ME -n mynamespace"
#    return 0 2> /dev/null || exit 0
#}

NAMESPACE_ARGS=""
#if [[ $1 == "-n" ]]; then
#  if [[ -z $2 ]]; then
#      usage
#      exit 0
#  fi
#
#  NAMESPACE_ARGS="-n $2"
#fi

function usage() {
  ME=$(basename $0)
    echo "Executes a pod for debugging purposes"
    echo ""
    echo "USAGE:"
    echo "$ME -a name"
    echo ""
    echo "EXAMPLES:"
    echo "$ME"
    echo "$ME -a something"
    return 0 2> /dev/null || exit 0
}

if [[ $* == "-h" ]]; then
  usage
  exit 0
fi

ME=$(whoami)
POD_NAME="debug-pod-$ME"

if [[ $1 == "-a" ]]; then
  if [[ -z $2 ]]; then
      usage
      exit 0
  fi

  POD_NAME="$2"
fi


TEMPLATE_FILE=$(realpath $(dirname $0))/pod.yaml
YAML_FILE="/tmp/debugger-$POD_NAME.yaml"
sed "s/\$POD_NAME/$POD_NAME/" $TEMPLATE_FILE > $YAML_FILE

kubectl $NAMESPACE_ARGS apply -f $YAML_FILE

kubectl $NAMESPACE_ARGS wait --for=condition=ready pod -l app=$POD_NAME --timeout 300s
kubectl $NAMESPACE_ARGS exec -it "$POD_NAME" -- bash

kubectl $NAMESPACE_ARGS delete -f $YAML_FILE || true
