kind: Pod
apiVersion: v1
metadata:
  name: $POD_NAME
  labels:
    app: $POD_NAME
spec:
  containers:
  - name: debugger
    image: yngvark/linuxtools
  dnsPolicy: Default
  terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: $POD_NAME
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: $POD_NAME
  type: ClusterIP
  #type: NodePort
